repos:
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: python -m pytest test_main.py  # Use 'python -m' to help with paths
        language: system
        pass_filenames: false
        always_run: true

